import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const debugUrl=process.env.BROWSER_DEBUG_URL,gameUrl=process.env.GAME_URL;
if(!debugUrl||!gameUrl)throw new Error('Set BROWSER_DEBUG_URL and GAME_URL before running browser checks');
const tabs=await (await fetch(new URL('/json/list',debugUrl))).json();
const tab=tabs.find(t=>t.type==='page'&&t.url.startsWith(gameUrl));
if(!tab)throw new Error('Training page missing');
const ws=new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});
let id=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{
 const message=JSON.parse(e.data);
 if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);
 if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result)}
};
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
const evaluate=async expression=>{
 const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});
 if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));
 return r.result.value;
};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
await send('Runtime.enable');
await evaluate("localStorage.removeItem('hunter-talents-v2')");
await send('Page.reload',{ignoreCache:true});await wait(2000);
assert.equal(await evaluate("document.querySelectorAll('#actionBar .action').length"),62);
assert.equal(await evaluate("document.querySelectorAll('#talentTrees .talent').length"),51);
await evaluate("document.getElementById('talentBtn').click()");
assert.equal(await evaluate("document.getElementById('talentPanel').classList.contains('hidden')"),false);
await evaluate("document.querySelector('#talentTrees .talent').click()");
assert.equal(await evaluate("document.getElementById('pointsBadge').textContent"),'1/51');
await evaluate("document.getElementById('talentClose').click()");
const tabsResult=await evaluate("Array.from(document.querySelectorAll('#spellTabs button')).map(b=>{b.click();return {page:b.textContent,count:document.querySelectorAll('#actionBar .action:not([hidden])').length}})");
assert.ok(tabsResult.every(t=>t.count>0));
await evaluate("document.getElementById('trainingBtn').click()");
assert.equal(await evaluate("document.querySelectorAll('#petFamilyOption option').length"),19);
const capture=await send('Page.captureScreenshot',{format:'png'});
await writeFile(process.argv[2]+'/hunter-training-panel.png',Buffer.from(capture.data,'base64'));
await evaluate("document.getElementById('callPetBtn').click()");
await wait(100);
assert.ok((await evaluate("document.getElementById('petVitals').textContent")).includes('Cat'));
await evaluate("document.getElementById('petAttack').click();document.querySelector('#spellTabs button').click()");
await wait(3000);
assert.ok((await evaluate("document.getElementById('petVitals').textContent")).includes('attack'));
await evaluate("document.getElementById('keybindBtn').click()");
assert.ok(await evaluate("document.querySelectorAll('#bindingGroups .binding-row').length>80"));
await evaluate("document.getElementById('keybindClose').click()");
await send('Page.reload',{ignoreCache:true});await wait(1200);
assert.equal(await evaluate("document.getElementById('pointsBadge').textContent"),'1/51');
const gameplay=await send('Page.captureScreenshot',{format:'png'});
await writeFile(process.argv[2]+'/hunter-gameplay.png',Buffer.from(gameplay.data,'base64'));
await evaluate("document.getElementById('resetBtn').click()");
await wait(100);
assert.equal(await evaluate("document.querySelector('[data-spell=MongooseBite]').classList.contains('unavailable')"),true);
assert.equal(await evaluate("document.querySelector('[data-spell=ArcaneShot]').classList.contains('unavailable')"),false);
await send('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyW',key:'w',windowsVirtualKeyCode:87});
const deadline=Date.now()+8000;
while(Date.now()<deadline){
 if(await evaluate("parseFloat(document.getElementById('rangeText').textContent)<=4.7"))break;
 await wait(50);
}
await send('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyW',key:'w',windowsVirtualKeyCode:87});
await wait(100);
assert.ok(await evaluate("parseFloat(document.getElementById('rangeText').textContent)<=5"));
const availability=await evaluate("Object.fromEntries(['ArcaneShot','AimedShot','MultiShot','SerpentSting','ScorpidSting','RaptorStrike','MongooseBite','HuntersMark'].map(id=>{const b=document.querySelector('[data-spell='+id+']');return [id,{grey:b.classList.contains('unavailable'),reason:b.dataset.unavailableReason,aria:b.getAttribute('aria-disabled')}]}))");
for(const id of ['ArcaneShot','AimedShot','MultiShot','SerpentSting','ScorpidSting'])assert.equal(availability[id].reason,'range',id);
assert.equal(availability.RaptorStrike.grey,false);
assert.equal(availability.MongooseBite.reason,'proc');
assert.equal(availability.HuntersMark.grey,false);
const meleeShot=await send('Page.captureScreenshot',{format:'png'});
await writeFile(process.argv[2]+'/hunter-melee-availability.png',Buffer.from(meleeShot.data,'base64'));
assert.equal(errors.length,0,JSON.stringify(errors));
console.log(JSON.stringify({status:'passed',actions:62,talents:51,petFamilies:19,tabs:tabsResult,runtimeErrors:errors.length,availability}));
ws.close();
