import {normalizeLoadout,DEFAULT_LOADOUT} from './equipment.js';
export function createEquipmentPanel({app,setModal,getLoadout,applyLoadout,getCombat}){
 const panel=document.createElement('div');panel.id='equipmentPanel';panel.className='modal hidden';
 const fields=[['meleeAP','Melee attack power',50000],['rangedAP','Ranged attack power',50000],['agility','Agility',50000],['intellect','Intellect',50000],['crit','Physical crit (%)',100],['hit','Physical hit (%)',100],['expertise','Expertise (points)',100],['dodge','Dodge (%)',100],['parry','Parry (%)',100],['armor','Armor',50000],['health','Health',50000],['mana','Mana',50000],['ammoDps','Ammo DPS',50000]];
 const input=(key,label,min,max,step=1)=>`<label class="equipment-field">${label}<input data-field="${key}" type="number" min="${min}" max="${max}" step="${step}" required></label>`;
 panel.innerHTML=`<form class="equipment-card"><div class="drawer-head"><div><div class="eyebrow">LEVEL 60 HUNTER</div><h2>Stats &amp; weapons</h2></div><button type="button" id="equipmentClose" class="close" aria-label="Close stats and weapons">×</button></div><p>Enter unbuffed totals <b>before talents and aspects</b>. Attack power, crit and dodge already include your base attributes and gear. Talent bonuses are added in combat.</p><fieldset><legend>Character</legend><div class="equipment-grid">${fields.map(([key,label,max])=>input('stats.'+key,label,['health','mana'].includes(key)?1:0,max,.1)).join('')}</div></fieldset><fieldset><legend>Melee equipment</legend><label class="equipment-field">Weapon setup<select data-field="mode"><option value="twoHand">Two-handed weapon</option><option value="dualWield">Two one-handed weapons</option></select></label><p>Raptor replaces the next main-hand swing. Off-hand swings continue independently at 50% damage, modified by Predator’s Edge. Dual-wield adds 19 percentage points of miss chance to white swings only.</p></fieldset>${[['ranged','Ranged weapon'],['twoHand','Two-handed weapon'],['mainHand','Main hand · one-handed'],['offHand','Off hand · one-handed']].map(([key,label])=>`<fieldset data-weapon="${key}"><legend>${label}</legend><div class="equipment-grid">${input(key+'.min','Minimum damage',0,10000)}${input(key+'.max','Maximum damage',0,10000)}${input(key+'.speed','Speed (seconds)',.5,6,.01)}${['mainHand','offHand'].includes(key)?`<label><input data-field="${key}.dagger" type="checkbox"> Dagger (normalized speed 1.7)</label>`:''}</div><small>Weapon tooltip damage, before attack power${key==='ranged'?' and ammo':''}.</small></fieldset>`).join('')}<fieldset><legend>Target &amp; incoming attacks</legend><p>The dummy faces toward the starting position. Attack from behind to avoid parries and blocks; NPCs can still dodge. Enable Dummy sparring in Training options for incoming attacks.</p><div class="equipment-grid">${input('target.level','Target level',60,63)}${input('target.blockValue','Block value',0,10000)}${input('target.attackSpeed','Sparring swing (seconds)',.5,10,.1)}${input('target.damage','Sparring damage before armor',0,10000)}<label><input data-field="target.canParry" type="checkbox"> Target can parry</label><label><input data-field="target.parryHaste" type="checkbox"> Target parry haste</label><label><input data-field="target.canBlock" type="checkbox"> Target can block</label></div></fieldset><div id="equipmentSummary" class="equipment-summary"></div><p id="equipmentStatus" role="status"></p><div class="equipment-footer"><button type="button" id="equipmentDefaults">Restore defaults</button><button type="submit" id="equipmentApply">Apply &amp; reset encounter</button></div></form>`;
 app.append(panel);const form=panel.querySelector('form'),$=id=>document.getElementById(id);
 function visibility(){const dual=form.querySelector('[data-field="mode"]').value==='dualWield';for(const el of form.querySelectorAll('[data-weapon]'))el.hidden=el.dataset.weapon==='twoHand'?dual:['mainHand','offHand'].includes(el.dataset.weapon)?!dual:false}
 function display(value){for(const el of form.querySelectorAll('[data-field]')){const v=el.dataset.field.split('.').reduce((o,k)=>o[k],value);if(el.type==='checkbox')el.checked=v;else el.value=v}visibility()}
 function summary(){const c=getCombat(),s=c.stats(),table=c.attackTable('Melee Swing');$('equipmentSummary').textContent=`Current combat: ${Math.round(s.melee)} melee AP · ${Math.round(s.ranged)} ranged AP · ${(s.crit*100).toFixed(1)}% crit before target suppression. Main-hand white table: ${(table.miss*100).toFixed(1)}% miss · ${(table.dodge*100).toFixed(1)}% dodge · ${(table.parry*100).toFixed(1)}% parry. Encounter outcomes: ${Object.entries(c.outcomes).map(([k,v])=>k+' '+v).join(' · ')||'none yet'}.`}
 form.querySelector('[data-field="mode"]').onchange=visibility;
 $('equipmentClose').onclick=()=>setModal('equipmentPanel',false);
 $('equipmentDefaults').onclick=()=>{display(normalizeLoadout(DEFAULT_LOADOUT));$('equipmentStatus').textContent='Defaults loaded into the form. Apply to use them.'};
 form.onsubmit=e=>{e.preventDefault();const raw={stats:{},ranged:{},twoHand:{},mainHand:{},offHand:{},target:{}};for(const el of form.querySelectorAll('[data-field]')){const parts=el.dataset.field.split('.'),key=parts.pop(),obj=parts.reduce((o,k)=>o[k],raw);obj[key]=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:Number(el.value)}for(const key of ['ranged','twoHand','mainHand','offHand'])if(raw[key].min>raw[key].max){$('equipmentStatus').textContent='Minimum weapon damage must not exceed maximum damage.';return}const saved=applyLoadout(normalizeLoadout(raw));summary();$('equipmentStatus').textContent=saved?'Applied and saved · encounter reset.':'Applied for this session · browser storage unavailable.'};
 panel.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();e.stopPropagation();setModal('equipmentPanel',false)}});
 return {open(){display(getLoadout());summary();$('equipmentStatus').textContent='Changes take effect when you apply.';setModal('equipmentPanel',true)}};
}
