export const WEAVE_GUIDE=`
<div class="help-card weave-guide"><button class="close" id="howToClose" aria-label="Close guide">×</button>
<div class="eyebrow">HOW TO · SURVIVAL</div><h2>SV melee weaving</h2>
<p class="guide-lead">Shoot from the edge of ranged range, step in for a melee swing, then return. Follow the swing timers and ability priority; this is not a fixed button sequence.</p>
<div class="guide-build"><strong>Forever SV Weave · 0 / 20 / 31</strong><span>No pet · Lone Wolf · single melee weapon</span><button class="inline" id="guidePreset">Load SV Weave &amp; reset encounter</button><small>Replaces your talents, dismisses your pet, removes the offhand and starts you 0.25 yd beyond the current ranged minimum. Training weapons stay equipped.</small></div>
<h3>1. Set up</h3><p>Use <b>Aspect of the Hawk</b>, <b>Trueshot Aura</b> and tracking that matches the target (the default dummy is a Humanoid). Apply <b>Hunter’s Mark</b>. Keep Auto Shot on and face the dummy. It resumes automatically when you return to ranged distance; the bow button beside its timer or your Auto Shot key toggles it manually. Stay just outside your ranged minimum: <b>8 yd + your combat reach + target combat reach</b> (<b>11 yd</b> with the default 1.5 yd reach for each unit); melee is within <b>5 yd</b> by default. Larger target reach extends both boundaries; melee never falls below 5 yd.</p>
<h3>2. Read the two swing bars</h3><div class="guide-cycle"><span>RANGED<br><b>11+ yd*</b></span><i>→</i><span>MELEE<br><b>≤ 5 yd*</b></span><i>→</i><span>RETURN<br><b>11+ yd* · stop</b></span></div><p>*Default human combat reaches. Green marks melee/weave range, amber the dead zone, and gold the ranged boundary. The red ring visualizes target combat reach as a training aid. Use the ground labels for your current setting.</p>
<p>Move in when your melee swing will be ready on arrival and Auto Shot has enough time for the wider run before its next windup. With the default reaches, a run from 11 to 5 yd takes about <b>0.86 s</b> at normal forward/strafe speed. A freshly released Auto is a useful opening if melee is ready. If Auto is nearly due, stay still and let it fire first.</p>
<p>Queue <b>Raptor Strike</b> once you enter melee when it is ready, then let the main-hand swing land. It replaces that white swing. The simulator queues this automatically; here you press the ability. Return promptly after the hit rather than waiting for another swing. Strafe while keeping the target in front; backpedaling is slower.</p>
<h3>3. Ability priority</h3><ol>
<li><b>Keep Hunter’s Mark active.</b> It also enables Expose Prey to trigger Mongoose Bite.</li>
<li><b>Take a safe melee swing window.</b> Use Raptor Strike when ready. Use <b>Mongoose Bite</b> when its proc is available, then <b>Strider Kick</b> when usable; do not linger in melee just to wait for a cooldown.</li>
<li><b>Apply Serpent Sting when absent.</b> Let it finish instead of repeatedly refreshing it. Scorpid and Viper Sting replace it.</li>
<li><b>Arcane Shot</b> when ready and in range.</li>
<li><b>Multi-Shot</b> if its cast plus your run into melee fits before the next planned swing. This preset leaves <b>Aimed Shot</b> out of the priority. Aimed and Multi share a cooldown here.</li>
</ol><p>Use <b>Rapid Fire</b> during sustained ranged uptime (Forever starts its cooldown priority after 5 seconds). Its faster ranged cycle leaves less room to weave. Recheck the timer before every run.</p>
<h3>4. Protect the windup</h3><p>Auto Shot can wind up and fire during another spell cast. <b>Moving during its 0.5 s windup cancels it.</b> Cast spells also require you to stand still. The default 5–11 yd gap is the dead zone: keep moving through it. Larger target combat reach moves both melee and ranged boundaries outward. Adjust Target combat reach in Training; the red reach ring and colored ground zones update together. Combat reach is separate from body radius.</p>
<p>In this training game, a melee swing resets the ranged swing. The Auto bar starts from zero as you return to range, even while moving. Stop before its final 0.5 s windup; stopping does not reset the bar again. A 3.0 s bow takes 3.0 s total, with windup in the last 0.5 s. Moving during windup triggers 0.5 s retries until you stop. Some ranged delay is therefore expected; compare consistent attempts rather than chasing zero delay.</p>
<h3>5. Measure a clean weave</h3><p>Watch <b>completed weaves</b>, <b>time inside</b>, <b>return → shot</b> and <b>interrupted windups</b>. Aim for one main-hand swing per trip, quick returns and no movement clips. The green GO cue suggests a post-shot opening; always check the melee bar and range too.</p>
<div class="guide-keys" id="guideKeys"></div><p>Set any Unbound abilities in <b>Keybinds</b>. Strider Kick is on the Attacks &amp; control page; Trueshot Aura is on Aspects &amp; auras.</p><p class="guide-note">Talents and priority follow Forever’s SV Weave preset. This arena uses fixed training gear and a simplified encounter; it does not reproduce the preset’s raid buffs, consumables or simulated DPS.</p>
<button class="inline" id="howToPlay">Back to training</button></div>`;
